### ISSUE TITLE
Disable Combat Aim Correction flag causing NPCs to become very inaccurate

### ISSUE THREAD

**Issue by zhongjiedong** [radj307/Another-Archery-Patcher#1]
**Describe the bug**
NPCs are not able to able properly

**To Reproduce**  
Use patcher with default settings

**Additional context**
I'm pretty sure that the global option to add the Disable Combat Aim Correction flag to the projectiles just completely destroys the NPCs ability to aim. With this flag on, NPCs would consistently shoot above my head about 1m, after patching without this flag they were far better.

I'm entirely sure if it's related to something else in my load order: https://loadorderlibrary.com/lists/tsukiro-11

If you can see anything that stands out let me know, but I think it might be best to not have that option as default.

**Comment by radj307** [comment]
From what I can tell it appears to be the result of many subtle changes to factors that influence enemy AI (projectile physics, bow physics, bow mods, enemy AI, aim correction being disabled, etc.)

The disable combat aim correction flag didn't cause any major issues with enemy aim during my testing, but it's also important to note that I tested it with a _much_ lighter load order -- so it's very unlikely to be comparable to what you're experiencing.

I agree that experimental changes like this shouldn't be enabled by default, so I'm going to update them to reflect that. Thanks for the report!

**Comment by radj307** [comment]
Fixed in e892853
